### ISSUE TITLE
Dependencies in file cannot be cloned

### ISSUE THREAD

**Issue by isJunCheng** [EMCP/faster-rcnn#1]
Hello, may I ask why the git path contained in the file(requirements.txt) cannot be cloned?

**Comment by EMCP** [comment]
paths for cloning and pip installing are different, did you encounter an error pip installing or??

in order to clone, use this 

```
git clone https://github.com/EMCP/faster-rcnn-private-pypi-libs
```

**Comment by EMCP** [comment]
#2 patches this 

Thanks @Holden-Mc
